In [9]:
import pandas as pd

data = pd.read_csv('Combined Data.csv')
data=data.dropna()

data

observation_date  CRUDE OIL  NATURAL GAS   GOLD  SILVER
0           9/10/2018      76.77         2.90  11.33   19.20
1            9/7/2018      75.55         2.88  11.30   19.20
2            9/6/2018      75.67         2.93  11.54   19.28
3            9/5/2018      76.68         3.00  11.24   19.45
4            9/4/2018      77.51         2.96  11.42   19.45
5           8/31/2018      76.94         2.98  10.96   17.65
6           8/30/2018      77.05         2.96  11.41   18.19
7           8/29/2018      76.07         2.96  11.25   18.08
8           8/28/2018      75.91         2.98  11.46   18.80
9           8/24/2018      74.41         2.99  11.71   19.28
10          8/23/2018      73.73         3.01  11.60   19.52
11          8/22/2018      72.96         3.02  11.81   19.60
12          8/21/2018      71.65         3.01  11.86   19.41
13          8/20/2018      71.11         3.04  12.40   19.45
14          8/17/2018      70.14         3.01  12.89   19.00
15          8/16/2018      69.21         3.02  13.39   19.64
16          8/15/2018      68.38         3.02  13.16   20.70
17          8/14/2018      70.77         3.02  11.88   18.11
18          8/13/2018      70.62         2.92  11.73   18.52
19          8/10/2018      71.00         2.96  11.78   17.90
20           8/9/2018      70.55         3.02  10.99   17.90
21           8/8/2018      70.71         2.99  11.43   17.90
22           8/7/2018      72.31         2.95  11.11   18.28
23           8/6/2018      72.51         2.85  11.02   17.52
24           8/3/2018      72.48         2.86  10.77   17.48
25           8/2/2018      72.95         2.77  11.08   17.93
26           8/1/2018      72.28         2.80  10.91   17.67
27          7/31/2018      74.16         2.82  11.21   17.17
28          7/30/2018      74.99         2.75  11.18   17.35
29          7/27/2018      74.84         2.78  11.05   17.17
...               ...        ...          ...    ...     ...
1841        4/28/2011     126.59         4.38  17.82   52.99
1842        4/27/2011     124.94         4.35  17.76   52.01
1843        4/26/2011     124.55         4.32  17.30   50.87
1844        4/21/2011     123.64         4.33  15.70   47.16
1845        4/20/2011     124.26         4.33  16.38   43.06
1846        4/19/2011     121.35         4.19  16.31   40.56
1847        4/18/2011     121.69         4.23  16.73   43.75
1848        4/15/2011     124.63         4.21  15.78   41.56
1849        4/14/2011     122.74         4.12  15.06   40.42
1850        4/13/2011     122.70         4.14  14.72   39.51
1851        4/12/2011     121.33         4.08  15.65   40.06
1852        4/11/2011     126.46         4.05  15.26   40.23
1853         4/8/2011     126.30         4.05  15.59   37.08
1854         4/7/2011     122.90         4.12  15.74   36.11
1855         4/6/2011     123.01         4.17  16.05   36.59
1856         4/5/2011     122.87         4.22  16.41   36.48
1857         4/4/2011     120.07         4.21  15.82   36.46
1858         4/1/2011     118.63         4.32  16.24   37.09
1859        3/31/2011     116.94         4.32  17.16   37.77
1860        3/30/2011     115.35         4.25  15.91   38.10
1861        3/29/2011     115.58         4.27  16.40   39.07
1862        3/28/2011     115.95         4.35  17.09   39.99
1863        3/25/2011     115.45         4.13  16.95   39.55
1864        3/24/2011     115.41         4.27  17.61   40.59
1865        3/23/2011     115.65         4.18  16.83   39.18
1866        3/22/2011     115.63         4.05  16.63   40.36
1867        3/21/2011     114.92         3.99  17.01   40.68
1868        3/18/2011     114.13         3.98  18.10   42.30
1869        3/17/2011     114.18         3.85  18.16   44.75
1870        3/16/2011     110.96         3.86  18.74   45.97

[1871 rows x 5 columns]

In [32]:
# split data table into data X and class labels y

X = data.ix[:,1:5].values
y = data.ix[:,4].values

X

array([[  76.77,    2.9 ,   11.33,   19.2 ],
       [  75.55,    2.88,   11.3 ,   19.2 ],
       [  75.67,    2.93,   11.54,   19.28],
       ..., 
       [ 114.13,    3.98,   18.1 ,   42.3 ],
       [ 114.18,    3.85,   18.16,   44.75],
       [ 110.96,    3.86,   18.74,   45.97]])

In [33]:

from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(X)

In [44]:
X_std


array([[-0.15472106, -0.4058575 , -1.23597605, -1.10630982],
       [-0.19667673, -0.43046329, -1.24218275, -1.10630982],
       [-0.19254994, -0.36894881, -1.19252919, -1.09812318],
       ..., 
       [ 1.13008529,  0.92285533,  0.16466817,  1.25758215],
       [ 1.13180478,  0.76291767,  0.17708156,  1.50829796],
       [ 1.02106933,  0.77522057,  0.29707767,  1.63314421]])

In [34]:
import numpy as np
mean_vec = np.mean(X_std, axis=0)
cov_mat = (X_std - mean_vec).T.dot((X_std - mean_vec)) / (X_std.shape[0]-1)
print('Covariance matrix \n%s' %cov_mat)

Covariance matrix 
[[ 1.00053476  0.56869761  0.33094506  0.46959295]
 [ 0.56869761  1.00053476  0.11431428  0.20985645]
 [ 0.33094506  0.11431428  1.00053476  0.85201429]
 [ 0.46959295  0.20985645  0.85201429  1.00053476]]


In [35]:
print('NumPy covariance matrix: \n%s' %np.cov(X_std.T))

NumPy covariance matrix: 
[[ 1.00053476  0.56869761  0.33094506  0.46959295]
 [ 0.56869761  1.00053476  0.11431428  0.20985645]
 [ 0.33094506  0.11431428  1.00053476  0.85201429]
 [ 0.46959295  0.20985645  0.85201429  1.00053476]]


In [36]:
cov_mat = np.cov(X_std.T)

eig_vals, eig_vecs = np.linalg.eig(cov_mat)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[-0.49777387 -0.42540269 -0.74121065 -0.147853  ]
 [-0.35565649 -0.68818453  0.6323415   0.00739793]
 [-0.535036    0.47229369  0.22085218 -0.66475519]
 [-0.5826372   0.34981891  0.04444458  0.73224675]]

Eigenvalues 
[ 2.31223649  1.16694917  0.38860089  0.13435249]


In [37]:
cor_mat1 = np.corrcoef(X_std.T)

eig_vals, eig_vecs = np.linalg.eig(cor_mat1)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[-0.49777387 -0.42540269 -0.74121065 -0.147853  ]
 [-0.35565649 -0.68818453  0.6323415   0.00739793]
 [-0.535036    0.47229369  0.22085218 -0.66475519]
 [-0.5826372   0.34981891  0.04444458  0.73224675]]

Eigenvalues 
[ 2.31100066  1.16632546  0.3883932   0.13428068]


In [38]:
cor_mat2 = np.corrcoef(X.T)

eig_vals, eig_vecs = np.linalg.eig(cor_mat2)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[-0.49777387 -0.42540269 -0.74121065 -0.147853  ]
 [-0.35565649 -0.68818453  0.6323415   0.00739793]
 [-0.535036    0.47229369  0.22085218 -0.66475519]
 [-0.5826372   0.34981891  0.04444458  0.73224675]]

Eigenvalues 
[ 2.31100066  1.16632546  0.3883932   0.13428068]


In [39]:
for ev in eig_vecs:
    np.testing.assert_array_almost_equal(1.0, np.linalg.norm(ev))
print('Everything ok!')

Everything ok!


In [40]:

# Make a list of (eigenvalue, eigenvector) tuples
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]

# Sort the (eigenvalue, eigenvector) tuples from high to low
eig_pairs.sort()
eig_pairs.reverse()

# Visually confirm that the list is correctly sorted by decreasing eigenvalues
print('Eigenvalues in descending order:')
for i in eig_pairs:
    print(i[0])

Eigenvalues in descending order:
2.31100065826
1.16632546291
0.388393195309
0.134280683516


In [46]:
import plotly.plotly as py
from plotly.graph_objs import *
import plotly.tools as tls

tot = sum(eig_vals)
var_exp = [(i / tot)*100 for i in sorted(eig_vals, reverse=True)]
cum_var_exp = np.cumsum(var_exp)

trace1 = Bar(
        x=['PC %s' %i for i in range(1,5)],
        y=var_exp,
        showlegend=False)

trace2 = Scatter(
        x=['PC %s' %i for i in range(1,5)], 
        y=cum_var_exp,
        name='cumulative explained variance')

data = Data([trace1, trace2])

layout=Layout(
        yaxis=YAxis(title='Explained variance in percent'),
        title='Explained variance by different principal components')

fig = Figure(data=data, layout=layout)
py.iplot(fig)

ModuleNotFoundError: No module named 'plotly'